export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ALL_TRIPS = 'GET_ALL_TRIPS';
export const GET_ALL_TRIPS_BY_USER_ID = 'GET_ALL_TRIPS_BY_USER_ID';
export const GET_TRIP_BY_TRIP_ID = 'GET_TRIP_BY_TRIP_ID';
export const TRIP_LOADING = 'TRIP_LOADING';
export const CLEAR_CURRENT_TRIP = 'CLEAR_CURRENT_TRIP';
export const TRIP_NOT_FOUND = 'TRIP_NOT_FOUND';
export const CREATE_TRIP = 'CREATE_TRIP';
export const DELETE_TRIP_BY_TRIP_ID = 'DELETE_TRIP_TRIP_ID';

export const GET_ALL_STOPS = 'GET_ALL_STOPS';
export const GET_ALL_STOPS_BY_USER_ID = 'GET_ALL_STOPS_BY_USER_ID';
export const GET_ALL_STOPS_BY_TRIP_ID = 'GET_ALL_STOPS_BY_TRIP_ID';
export const GET_STOP_BY_STOP_ID = 'GET_STOP_BY_STOP_ID';
export const STOP_LOADING = 'STOP_LOADING';
export const CLEAR_CURRENT_STOP = 'CLEAR_CURRENT_STOP';
export const STOP_NOT_FOUND = 'STOP_NOT_FOUND';
export const CREATE_STOP = 'CREATE_STOP';
export const DELETE_STOP_BY_STOP_ID = 'DELETE_STOP_BY_STOP_ID';

export const GET_ALL_DAYS = 'GET_ALL_DAYS';
export const GET_ALL_DAYS_BY_USER_ID = 'GET_ALL_DAYS_BY_USER_ID';
export const GET_ALL_DAYS_BY_STOP_ID = 'GET_ALL_DAYS_BY_STOP_ID';
export const GET_DAY_BY_DAY_ID = 'GET_DAY_BY_DAY_ID';
export const DAY_LOADING = 'DAY_LOADING';
export const CLEAR_CURRENT_DAY = 'CLEAR_CURRENT_DAY';
export const DAY_NOT_FOUND = 'DAY_NOT_FOUND';
export const CREATE_DAY = 'CREATE_DAY';
export const DELETE_DAY_BY_DAY_ID = 'DELETE_DAY_BY_DAY_ID';

export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_ALL_EVENTS_BY_USER_ID = 'GET_ALL_EVENTS_BY_USER_ID';
export const GET_ALL_EVENTS_BY_DAY_ID = 'GET_ALL_EVENTS_BY_STOP_ID';
export const GET_EVENT_BY_EVENT_ID = 'GET_EVENT_BY_EVENT_ID';
export const EVENT_LOADING = 'EVENT_LOADING';
export const CLEAR_CURRENT_EVENT = 'CLEAR_CURRENT_EVENT';
export const EVENT_NOT_FOUND = 'EVENT_NOT_FOUND';
export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT_BY_EVENT_ID = 'DELETE_EVENT_BY_EVENT_ID';

export const DELETE_USER_BY_USER_ID = 'DELETE_USER_BY_USER_ID';
